### ISSUE TITLE
Module '"json-data-mapper"' has no exported member 'formatToSchema'

### ISSUE THREAD

**Issue by saraiyakush** [gkrthk/Json-data-mapper#1]
Hi,

I've installed this module using command
`npm i json-data-mapper --save`
and I import the function formatToSchema as below.
`import { formatToSchema } from 'json-data-mapper';`

The compiler complains
`TS2305: Module '"json-data-mapper"' has no exported member 'formatToSchema'`

**Comment by gkrthk** [comment]
Hi @saraiyakush, 
Thanks for reporting the issue. This is fixed in v1.0.3 and published.

**Comment by saraiyakush** [comment]
Thanks @gkrthk Issue fixed now. Works like a charm.
